replicaCount: 1
persistence:
  homarr-config:
    # -- Enable homarr-config persistent storage
    enabled: true
    # -- homarr-config storage class name
    storageClassName: "local-path"
    # -- homarr-config access mode
    accessMode: "ReadWriteOnce"
    # -- homarr-config storage size
    size: "50Mi"
    # -- homarr-config mount path inside the pod
    mountPath: "/app/data/configs"
  homarr-database:
    # -- Enable homarr-database persistent storage
    enabled: true
    # -- homarr-database storage class name
    storageClassName: "local-path"
    # -- homarr-database access mode
    accessMode: "ReadWriteOnce"
    # -- homarr-database storage size
    size: "50Mi"
    # -- homarr-database mount path inside the pod
    mountPath: "/app/database"
  homarr-icons:
    # -- Enable homarr-icons persistent storage
    enabled: true
    # -- homarr-icons storage class name
    storageClassName: "local-path"
    # -- homarr-icons access mode
    accessMode: "ReadWriteOnce"
    # -- homarr-icons storage size
    size: "50Mi"
    # -- homarr-icons mount path inside the pod
    mountPath: "/app/public/icons"
  homarrTrustedCerts:
    # -- Enable trusted certificates persistence
    enabled: false
    # -- Persistence mode can be : configmap (declarative), secret (declarative) or existingSecret (mount an existing Kubernetes Secret by name and specify which keys to mount as files)
    type: configmap
    # -- Name of the existing Kubernetes Secret to mount (required if type is "existingSecret")
    existingSecretName: ""
    # -- List of keys (filenames) to mount from the existing secret (used only when type is "existingSecret")
    existingSecretKeys:
      # - cert3.crt
      # - cert4.crt
    # -- homarr-trusted-certificates  mount path inside the pod
    mountPath: "/appdata/trusted-certificates"
    # -- homarr-trusted-certificates certificates, each entry will become a new trusted certificate as a dedicated file (works only for "configmap" and "secret" mode)
    certificates:
      # cert1.crt: |
      #   -----BEGIN CERTIFICATE-----
      #   MIICCDCCAXGgAwIBAgIUQPCQCEX+rA4L1c/fWkpXyP4bxyQwDQYJKoZIhvcNAQEL
      #   BQAwFjEUMBIGA1UEAwwLZXhhbXBsZS5jb20wHhcNMjUwMjI0MTcwMDQwWhcNMjYw
      #   MjI0MTcwMDQwWjAWMRQwEgYDVQQDDAtleGFtcGxlLmNvbTCBnzANBgkqhkiG9w0B
      #   AQEFAAOBjQAwgYkCgYEArn735D+W3NHBsFM72G4ltoB3awSG8tlOUv4UbyysCcVd
      #   lC6D9A2olM4hqvGU6P5gcA4C+3bSijxxDBfGjfrUU/XUYfdcQzWn4Z54hJxTcY61
      #   78PetjZ0SMUtQXXdaUKdbemYlVEgXBlTIzpqiMUDeow6kEtv9LMiImSowf94YOsC
      #   AwEAAaNTMFEwHQYDVR0OBBYEFDQoBSUt3ZyDxQP5rqavvpQxjbnkMB8GA1UdIwQY
      #   MBaAFDQoBSUt3ZyDxQP5rqavvpQxjbnkMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZI
      #   hvcNAQELBQADgYEACE6M0NmKgYQAZB9FsGRkSWJFbHPAC7LUQalpZhykus8iZHEx
      #   /b+C7kj+gRogphaE8869yW2WDO7t4QHLJXh/fsEU13biK7yHank0EEa7mVIy5MBp
      #   XnRFRotpLR8Xmzyb2LADxor3ZZbVpyGZ+Ic68kdeSCN//jo6WQEafN/xZho=
      #   -----END CERTIFICATE-----
      # cert2.crt: |
      #   -----BEGIN CERTIFICATE-----
      #   MIICAjCCAWugAwIBAgIUVpWs2tw4gpNahaT76q+XeVXd+hIwDQYJKoZIhvcNAQEL
      #   BQAwEzERMA8GA1UEAwwIdG90by5jb20wHhcNMjUwMjI0MTcwMTA4WhcNMjYwMjI0
      #   MTcwMTA4WjATMREwDwYDVQQDDAh0b3RvLmNvbTCBnzANBgkqhkiG9w0BAQEFAAOB
      #   jQAwgYkCgYEA0UxVYXJdBCv/XfWt6xUGrwmlJfDxOVt7qWJ9C9Z+1P/B7FIKeIiO
      #   BNkcGFXUbMlRsSJ2DG1t6un3CzpkinivkOuAyjoMzA58RGAOrRMyweZkER2j2B9Q
      #   iiY3WFNzl8KqPKsRBq2oS8FU72fzn1c7llNvKDIamSlVbKsc4yosIv8CAwEAAaNT
      #   MFEwHQYDVR0OBBYEFCn0xxFSJudync+Koeo8noSymQ2iMB8GA1UdIwQYMBaAFCn0
      #   xxFSJudync+Koeo8noSymQ2iMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQEL
      #   BQADgYEAFAklBGPb3ko+iOanMWVxHnX+ypVoYUqBP4g2OhbxIBVTWSRAOMQgvuan
      #   2V+U3ZUzzxPFYJTH6+IytoB8PqSHUrSFPGaAEZPjiqK/1L+FXECKqyra3o6QdTGq
      #   UeP5DExC1ADCMawZNf4o2cKPwdsVdx5x0mieB3qCshdviYBSTq8=
      #   -----END CERTIFICATE-----

